#! /bin/bash

#Create necessary directories
mkdir /etc/Ay-pSiphon/

#Download neccessary scripts and files
echo "Starting downloads"
wget -P /etc/Ay-pSiphon/ https://raw.githubusercontent.com/Psiphon-Labs/psiphon-tunnel-core-binaries/master/linux/psiphon-tunnel-core-x86_64 --quiet
wget -P /etc/Ay-pSiphon/ https://raw.githubusercontent.com/shammay-PC/Ay-pSiphon/main/pSiphon.config --quiet
wget -P /usr/bin/ https://raw.githubusercontent.com/shammay-PC/Ay-pSiphon/main/pSiphon --quiet
wget https://raw.githubusercontent.com/shammay-PC/Ay-pSiphon/refs/heads/main/UnAy-pSiphon --quiet
echo "Downloads finished"

echo " "
echo "Installing Ay-pSiphon"

#Give these files the executable permission
chmod +x /etc/Ay-pSiphon/psiphon-tunnel-core-x86_64
chmod +x /usr/bin/pSiphon 
echo "Ay-pSiphon Installation finished"

echo " "
echo "Running post install checks"
echo " "
echo "Checking if files exist (Phase 1/2)"
if test -f /etc/Ay-pSiphon/psiphon-tunnel-core-x86_64; then
  echo "pSiphon binary found"
else "ERROR: pSiphon binary not found"
fi

if test -f /etc/Ay-pSiphon/pSiphon.config; then
  echo "pSiphon configuration found"
else "ERROR: pSiphon configuration not found"
fi

if test -f /usr/bin/pSiphon; then
  echo "pSiphon startup script found"
else "ERROR: pSiphon startup script not found"
fi

if test -f UnAy-pSiphoner; then
  echo "pSiphon uninstall script found"
else "ERROR: pSiphon uninstall script not found"
fi

echo " "
echo "Checking if correct permssions have been applied (Phase 2/2)"

if test -x /etc/Ay-pSiphon/psiphon-tunnel-core-x86_64;
then
    echo "pSiphon binaries have correct permissions"
else
    echo "ERROR: pSiphon binaries do not have required permissions"
fi

if test -x /usr/bin/pSiphon;
then
    echo "pSiphon startup file has correct permissions"
else
    echo "ERROR: pSiphon startup file does not have required permission"
fi

echo " "
#Finish installer and give message
echo "Ay-pSiphon for Linux installation successfully completed. Run: psiphon	 to start the program. Please allow a reasonable amount for pSiphon to connect as it may take a while"

#Start the Ay-pSiphon
echo "Starting Ay-pSiphon . . ."
sudo psiphon
